<?php

/**
 * @file
 * Contains d8_testable_code_example.module.
 */

use Drupal\Component\Render\FormattableMarkup;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function d8_testable_code_example_node_presave(\Drupal\node\NodeInterface $node) {
  $generated_title = \Drupal::service('d8_testable_code_example.node_title_generator')
    ->generateTitle($node);
  $node->setTitle($generated_title);
}
