<?php

/**
 * @file
 * Contains d8_testable_code_example.module.
 */

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function d8_testable_code_example_node_presave(Drupal\Core\Entity\EntityInterface $entity) {
  // Updates the title to a fix string:
  // - Basic pages: "Page: @title"
  // - Articles: "Awesome article by @author".
  switch ($entity->bundle()) {
    case 'page':
      _d8_testable_code_page_title_generate($entity);
      break;
    case 'article':
      _d8_testable_code_article_title_generate($entity);
      break;
  }
}

/**
 * Set the title "Page: @title" to the given Node.
 * @param \Drupal\node\NodeInterface $node
 */
function _d8_testable_code_page_title_generate(\Drupal\node\NodeInterface $node) {
  $node->setTitle(t('Page: @title', ['@title' => $node->getTitle()]));
}

/**
 * Set the title "Awesome article by @author" to the given Node.
 * @param \Drupal\node\NodeInterface $node
 */
function _d8_testable_code_article_title_generate(\Drupal\node\NodeInterface $node) {
  $node->setTitle(t('Awesome article by @author', ['@author' => $node->getOwner()->getAccountName()]));
}
